name: Build and Release

on:
   workflow_dispatch:
   push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build and Release
        run: |
          
          #!/usr/bin/env sh
          set -x
          VERSION="2023.5.0"
          DATE=$(date -u '+%Y-%m-%d-%H%M UTC')
          VERSION_FLAGS="-X \"main.Version=${VERSION}\" -X \"main.BuildTime=${DATE}\""
          NAME=c.js 
          SRC="github.com/cloudflare/cloudflared/cmd/cloudflared"
          
          rm -rf ./release
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build                     -mod=vendor -ldflags="${VERSION_FLAGS} -w -s" -o release/${NAME}_linux_arm64 ${SRC}
        
          

          # 创建一个 Release 并上传编译结果
          TAG_NAME="v${{ github.run_number }}"
          echo "Creating Release $TAG_NAME"
          UPLOAD_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST "https://api.github.com/repos/${{ github.repository }}/releases" -d "{\"tag_name\":\"$TAG_NAME\",\"name\":\"$TAG_NAME\"}" | jq -r .upload_url | sed "s/{?name,label}//")

          for entry in ./release/*
          do
            echo "Uploading: $entry"
            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/octet-stream" --data-binary @$entry "$UPLOAD_URL?name=$(basename $entry)"
          done
